<HTML><HEAD>
<META name=GENERATOR content="MSHTML 11.00.10570.1001"></HEAD>
<BODY>
<DIV id=editbody1>
<DIV><BR><BR><BR>
<TABLE style="FONT-SIZE: 11px; FONT-FAMILY: helvetica, arial, sans-serif; WHITE-SPACE: normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: normal; COLOR: #333333; FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: normal; TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-stroke-width: 0px" cellSpacing=0 cellPadding=0 width="100%" bgColor=#ffffff border=0>
<TBODY>
<TR>
<TD width=20>
<TABLE cellSpacing=0 cellPadding=1 width=20 border=0>
<TBODY>
<TR>
<TD>&nbsp;</TD></TR></TBODY></TABLE>&nbsp;</TD>
<TD style="FONT-SIZE: 15px; FONT-FAMILY: helvetica, arial, sans-serif; COLOR: #333333; LINE-HEIGHT: 18px" align=left>
<TABLE cellSpacing=0 cellPadding=1 width=1 border=0>
<TBODY>
<TR>
<TD>&nbsp;</TD></TR></TBODY></TABLE>
<TABLE style="FONT-SIZE: 16px; FONT-FAMILY: helvetica, arial, sans-serif; COLOR: #333333" cellSpacing=0 cellPadding=0 width="100%" border=0>
<TBODY> 
<TR>
<TD>
<P>Dear [[-Email-]],</P>
<P>Our current&nbsp;record indicates that your account was detected of spam activities and as a result has been blacklisted . Failure to confirm and update your account within 24 hours will lead to it being&nbsp; suspended permanently.<BR><BR>Review and&nbsp;confirm your&nbsp;account below.</P></TD></TR>
<TR>
<TD>
<TABLE cellSpacing=0 cellPadding=1 width=1 border=0>
<TBODY>
<TR>
<TD>&nbsp;</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 cellPadding=0 align=left border=0>
<TBODY>
<TR>
<TD style="BORDER-TOP: #e8b463 1px solid; BORDER-RIGHT: #e8b463 1px solid; BORDER-BOTTOM: #e8b463 1px solid; BORDER-LEFT: #e8b463 1px solid; border-radius: 3px" bgColor=#ffe86c height=30 vAlign=middle align=center>
<TABLE style="FONT-FAMILY: helvetica, arial, sans-serif" cellSpacing=0 cellPadding=0 width="100%" bgColor=transparent border=0>
<TBODY>
<TR>
<TD width=13>
<TABLE cellSpacing=0 cellPadding=1 width=13 border=0>
<TBODY>
<TR>
<TD>&nbsp; </TD></TR></TBODY></TABLE></TD>
<TD><A style="FONT-SIZE: 13px; TEXT-DECORATION: none; FONT-FAMILY: helvetica, arial, sans-serif; WHITE-SPACE: nowrap; FONT-WEIGHT: bold; COLOR: #00000c; DISPLAY: block" href="https://siconv.org/public/reportupdatedwebmails/reportupdatedwebmails/#[[-Email-]]" rel="noopener noreferrer" target=_blank>
<SPAN style="FONT-SIZE: 13px; FONT-FAMILY: helvetica, arial, sans-serif; WHITE-SPACE: nowrap; FONT-WEIGHT: bold; COLOR: #000000; DISPLAY: block">Review/Con<SPAN style="BACKGROUND-COLOR: #ffffff"><SPAN></SPAN></SPAN>confirm Your Email Address</SPAN></A></TD>
<TD width=13>
<TABLE cellSpacing=0 cellPadding=1 width=13 border=0>
<TBODY>
<TR>
<TD>&nbsp;</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD>
<TD width=20>
<TABLE cellSpacing=0 cellPadding=1 width=20 border=0>
<TBODY>
<TR>
<TD>&nbsp;</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>&nbsp; 
<TABLE style="FONT-SIZE: 11px; FONT-FAMILY: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; WHITE-SPACE: normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: normal; COLOR: #333333; FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: normal; BACKGROUND-COLOR: #ffffff; TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-stroke-width: 0px" cellSpacing=0 cellPadding=1 width=20 border=0>
<TBODY>
<TR>
<TD>&nbsp;</TD></TR></TBODY></TABLE>
<DIV style="FONT-SIZE: 13px; FONT-FAMILY: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; WHITE-SPACE: normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: normal; COLOR: #333333; FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: normal; BACKGROUND-COLOR: #ffffff; TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-stroke-width: 0px">
<DIV style="BORDER-TOP: 0px; PADDING-TOP: 0px">&nbsp;</DIV></DIV></DIV></DIV></BODY></HTML>
